### ISSUE TITLE
The reported FPS for GaussianAvatars is much lower than the original paper

### ISSUE THREAD

**Issue by ShenhanQian** [MingSun-Tse/LightAvatar-TensorFlow#1] opened 2024-09-29 20:12 UTC
Dear authors, I noticed that the reported FPS for GaussianAvatars in your appendix 
<img width="500" alt="image" src="https://github.com/user-attachments/assets/303fc852-86ba-4cb6-86a5-4a0dfff1c9c5">

is much lower than the original paper
<img width="464" alt="image" src="https://github.com/user-attachments/assets/216d74a3-d140-468b-a3fc-982bc1e50e0e">

Can you please provide more details on how you conducted this test?

**Comment by MingSun-Tse** [comment] 2024-10-01 19:35
Hi @ShenhanQian , thanks for noticing the potential problem and reaching out. By my best recall, I just run the code released on github and got the numbers. I am attending eccv now. Will do my best to replicate the experiment and let you know. Meanwhile, it would be great if you could instruct me to get the results in your paper in case I missed anything. Thanks!

**Comment by ShenhanQian** [comment] 2024-10-01 19:53
Hi @MingSun-Tse , thanks for your reply while attending the conference. I am wondering if you tested the FPS with our local viewer or the offline rendering script. 

For the reported FPS in our paper, we used the offline rendering script. We had to avoid counting in time spent on IO by commenting out the part that reads GT images from the dataset and the part that writes rendering results and GT images into the output folder.

**Comment by MingSun-Tse** [comment] 2024-10-01 20:32
Ok, i see! Can you prepare a script for benchmarking the speed and update it in your repo? I guess others would also be interested in the inference efficiency benchmarks. Tx!

**Comment by ShenhanQian** [comment] 2024-10-01 23:32
@MingSun-Tse Thanks for your suggestion. We have updated the repo for FPS benchmark. Please refer to commands [here](https://github.com/ShenhanQian/GaussianAvatars/blob/main/doc/offline_render.md#fps-benchmark).

We got 200+ FPS when rendering in 802x550 with an NVIDIA RTX A4000 as shown below:
![image](https://github.com/user-attachments/assets/f9635a28-9c13-415d-83b6-772c37f65fde)

**Comment by MingSun-Tse** [comment] 2024-10-11 05:15
Hi @ShenhanQian , thanks for your patience! I ran your speed benchmark script and confirmed the speed is around 200 FPS (on a 4090 24GB GPU). Thanks _a lot_ for letting us know about the problem! I'll update the paper soon. Regards,

<img width="1706" alt="image" src="https://github.com/user-attachments/assets/6e3b2885-9d34-42bc-bdc3-b6afb3325d9f">

**Comment by ShenhanQian** [comment] 2024-10-11 07:22
Thank you a lot for your spontaneous response. We are glad that the benchmark performance is consistent. Could you please leave a comment here after you have updated the paper?

Best regards,
Shenhan

**Comment by MingSun-Tse** [comment] 2024-10-26 15:00
Hi @ShenhanQian Thanks for your patience! I just got time to finish the benchmarks and update the paper. The updated results are below:

<img width="990" alt="image" src="https://github.com/user-attachments/assets/1f15cdf1-91a6-43d9-8470-ebff333555b2">

- The corresponding benchmark raw results are attached in the [pytorch .py code](https://github.com/MingSun-Tse/LightAvatar-TensorFlow/blob/19865a5adcb07c7dd9edd981ff0fe6335edaca62/speed_benchmark_pytorch.py#L990). 
- pdf updated [here](https://github.com/MingSun-Tse/LightAvatar-TensorFlow/blob/master/paper/lightavatar-eccv24-workshop-updated.pdf). The arxiv version will be updated soon.
- Terribly sorry I mis-evaluated your method before (I checked the logs, probably because I forgot to sync the CUDA and CPU before adding timing stamps..). Thanks again for pointing out our mistake! 

I am closing this issue now. Feel free to reopen it if you have further questions :-).

Regards,

**Closed as completed by MingSun-Tse** 2024-10-26 15:00 UTC
